// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Updata20191112451 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updata20191112451));
        
        string IMigrationMetadata.Id
        {
            get { return "201912040051296_Updata20191112451"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
