// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _201911111204 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201911111204));
        
        string IMigrationMetadata.Id
        {
            get { return "201912040153267_201911111204"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
